name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential

      - name: Build
        run: |
          mkdir build
          cd build
          cmake ..
          make -j$(nproc)
          mv qvm ../qvm-x86_64
          mv qas ../qas-x86_64
      
      - name: Upload artifact (qvm)
        uses: actions/upload-artifact@v4
        with:
          name: qvm-x86_64
          path: qvm-x86_64
      
      - name: Upload artifact (qas)
        uses: actions/upload-artifact@v4
        with:
          name: qas-x86_64
          path: qas-x86_64

  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: [ build ]

    steps:
      - name: Authenticate GitHub CLI
        run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Download artifact (qvm)
        uses: actions/download-artifact@v4
        with:
          name: qvm-x86_64

      - name: Download artifact (qas)
        uses: actions/download-artifact@v4
        with:
          name: qas-x86_64

      - name: Update Nightly Release
        uses: andelf/nightly-release@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: nightly-release
          name: 'Nightly Release'
          body: |
            Automated nightly release for commit ${{ github.sha }}. This release contains all of the newest features.
          files: |
            ./qvm-x86_64
            ./qas-x86_64
